services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5



  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3000:3000"


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["node", "worker.js"]